#!/usr/bin/env node
// Installer for the opencode adapter (#74).
//
//   node adapters/opencode/install.mjs              # global  (~/.config/opencode)
//   node adapters/opencode/install.mjs --project    # this project (./.opencode)
//   node adapters/opencode/install.mjs --dir <path> # somewhere explicit
//   node adapters/opencode/install.mjs --uninstall  # remove what it wrote
//   node adapters/opencode/install.mjs --print      # just show the stub
//
// What it writes is a ONE-LINE stub that re-exports the plugin from THIS
// checkout:
//
//   export { ClaudeHooksGuard } from "/abs/path/to/claude-hooks/adapters/opencode/plugin.js"
//
// so `git pull` in the checkout updates the guard with no reinstall, and there
// is still exactly one copy of the rules (the decide cores under core/).
//
// It writes the stub into BOTH `plugin/` and `plugins/` under the opencode
// config dir on purpose: the directory name changed between opencode versions
// (older: `plugin/`, current docs: `plugins/`), the wrong one is simply never
// read, and guessing wrong means the guard silently does nothing.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const STUB_NAME = "claude-hooks.js";
const PLUGIN = fileURLToPath(new URL("./plugin.js", import.meta.url));
const DIR_NAMES = ["plugin", "plugins"];

const argv = process.argv.slice(2);
const has = (flag) => argv.includes(flag);
const valueOf = (flag) => {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : undefined;
};

const stub = `// Generated by claude-hooks — adapters/opencode/install.mjs. Do not edit.
// The plugin (guards + observability) lives in the claude-hooks checkout; this
// file only points at it, so pulling that repo updates the guard in place.
export { ClaudeHooksGuard } from ${JSON.stringify(PLUGIN)};
`;

if (has("--print")) {
  process.stdout.write(stub);
  process.exit(0);
}

function configRoot() {
  const explicit = valueOf("--dir");
  if (explicit) return path.resolve(explicit);
  if (has("--project")) return path.resolve(process.cwd(), ".opencode");
  const xdg = process.env.XDG_CONFIG_HOME;
  return xdg ? path.join(xdg, "opencode") : path.join(os.homedir(), ".config", "opencode");
}

const root = configRoot();
// `--dir` may point straight at a plugin directory; anything else is a config
// root that owns plugin/ + plugins/ subdirectories.
const targets = path.basename(root) === "plugin" || path.basename(root) === "plugins"
  ? [root]
  : DIR_NAMES.map((d) => path.join(root, d));

if (has("--uninstall")) {
  let removed = 0;
  for (const dir of targets) {
    const file = path.join(dir, STUB_NAME);
    try {
      fs.unlinkSync(file);
      console.log(`removed  ${file}`);
      removed++;
    } catch (err) {
      if (err.code !== "ENOENT") console.error(`failed   ${file}: ${err.message}`);
    }
  }
  console.log(removed ? `\n${removed} stub(s) removed. Restart opencode.` : "\nnothing to remove.");
  process.exit(0);
}

if (!fs.existsSync(PLUGIN)) {
  console.error(`plugin not found: ${PLUGIN}`);
  process.exit(1);
}

let written = 0;
for (const dir of targets) {
  const file = path.join(dir, STUB_NAME);
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file, stub);
    console.log(`installed ${file}`);
    written++;
  } catch (err) {
    console.error(`failed    ${file}: ${err.message}`);
  }
}

if (!written) {
  console.error("\nnothing installed.");
  process.exit(1);
}

console.log(`
plugin source: ${PLUGIN}

next:
  1. restart opencode (plugins load at startup)
  2. verify the guard:   ask opencode to run  rm -rf /tmp/claude-hooks-guard-check
     → it must refuse with a "[claude-hooks/bash-guard]" message
  3. verify observation: open http://127.0.0.1:4090 → sessions tab
     (the session row is tagged "oc"; the collector starts on its own)

switches (export before launching opencode):
  CLAUDE_HOOKS_OC_NUDGES=off    safety blocks only, no style nudges
  CLAUDE_HOOKS_OC_ASK=allow     let 'git reset --hard' & co. through
  CLAUDE_HOOKS_OC_OBSERVE=off   no events to the collector
  CLAUDE_HOOKS_OC_GUARD=off     observation only, no blocking
  CLAUDE_HOOKS_OC_DEBUG=1       print internal errors to stderr
`);
